 NumPy (Numerical Python) is a powerful Python library used for scientific computing and data analysis. It provides:

Support for multidimensional arrays and matrices.

A wide range of mathematical functions to perform fast computations on large datasets.

Efficient handling of numerical data, making it a foundation for libraries like Pandas, SciPy, and scikit-learn

In [1]:
!pip install numpy


In [2]:
import numpy as np

In [3]:
import numpy as np 

files = ["master_results_table.csv",
         "mers_results.csv",
         "sars_results.csv"]



In [4]:
masters_results = [99.9,99,98.9,90,99]
mers_results  = [0.33334,0.0555,0.355,0.88,0.66667]
sars_result =  [0.776,0.333,0.555,0.567,0.334]

mers_results

[0.33334, 0.0555, 0.355, 0.88, 0.66667]

In [5]:
masters_results


[99.9, 99, 98.9, 90, 99]

In [6]:
sars_result

[0.776, 0.333, 0.555, 0.567, 0.334]

In [7]:
np.array(masters_results)

array([99.9, 99. , 98.9, 90. , 99. ])

In [8]:
np.array(sars_result)

array([0.776, 0.333, 0.555, 0.567, 0.334])

In [9]:
np.array(mers_results)

array([0.33334, 0.0555 , 0.355  , 0.88   , 0.66667])

In [10]:
#time
masters_results = [99.9,99,98.9,90,99]
mers_results  = [0.33334,0.0555,0.355,0.88,0.66667]
sars_result =  [0.776,0.333,0.555,0.567,0.334]

 
import time

start = time.time()

print("\nTime taken for masters_result:", time.time() - start)
print("\nTime taken for sars_result:", time.time() - start)
print("\nTime taken for mers_result:", time.time() - start)


Time taken for masters_result: 5.650520324707031e-05

Time taken for sars_result: 0.0006604194641113281

Time taken for mers_result: 0.0007843971252441406


In [11]:
#array
masters_results=[99.9,99,98.9,90,99]
array=np.array(masters_results)
print(array)

[99.9 99.  98.9 90.  99. ]


In [12]:
print(type(masters_results))
print(type(sars_result))

<class 'list'>
<class 'list'>


In [13]:
array.shape

(5,)

In [14]:
array.ndim

1

In [15]:
# logspace
import numpy as np
masters_results=np.logspace(1,3,3)
masters_results


array([  10.,  100., 1000.])

In [16]:
sars_result = np.logspace(2,3,3)
sars_result

array([ 100.        ,  316.22776602, 1000.        ])

In [17]:
mers_results= np.logspace(1,2,3)
mers_results

array([ 10.       ,  31.6227766, 100.       ])

In [18]:
# number of zeros
masters_results = np.zeros(2)
masters_results

array([0., 0.])

In [19]:
mers_results = np.zeros(5)
mers_results

array([0., 0., 0., 0., 0.])

In [20]:
sars_result = np.zeros(3)
sars_result

array([0., 0., 0.])

In [21]:
array = np.array(masters_results)

array.dtype

dtype('float64')

In [22]:
array = np.array(mers_results)
array.dtype

dtype('float64')

In [23]:
#arithmetic operation
masters_results =np.array ([99.9,99,98.9,90,99])
mers_results  = np.array([0.33334,0.0555,0.355,0.88,0.66667])
sars_result =  np.array([0.776,0.333,0.555,0.567,0.334])


print(masters_results+sars_result)


[100.676  99.333  99.455  90.567  99.334]


In [24]:
print(masters_results-sars_result)

[99.124 98.667 98.345 89.433 98.666]


In [25]:
print(masters_results*mers_results)

[33.300666  5.4945   35.1095   79.2      66.00033 ]


In [26]:
print(mers_results%sars_result)

[0.33334 0.0555  0.355   0.313   0.33267]


In [27]:
print(sars_result**mers_results)

[0.91893862 0.94079642 0.81137946 0.60695025 0.48138888]


In [28]:
#square root
print(np.sqrt(array))

[0. 0. 0. 0. 0.]


In [29]:
print(np.sqrt(masters_results))

[9.99499875 9.94987437 9.94484791 9.48683298 9.94987437]


In [30]:
print(np.sqrt(mers_results))

[0.57735604 0.23558438 0.59581876 0.93808315 0.81649862]


In [31]:
print(np.sqrt(sars_result))

[0.88090862 0.57706152 0.74498322 0.75299402 0.57792733]


In [32]:
#indexing 

print(array[3])

0.0


In [33]:
print(masters_results[4])

99.0


In [34]:
print(mers_results[0:4])

[0.33334 0.0555  0.355   0.88   ]


In [35]:
print(sars_result[2:3])

[0.555]


In [36]:

masters_results

array([99.9, 99. , 98.9, 90. , 99. ])

In [37]:
mers_results
print(mers_results[::3])

[0.33334 0.88   ]


In [38]:
# multidimensional array

mers_results = ([0.33,0.55,0.66],
                [0.44,0.65,0.23],
                [0.324,0.567,0.45])

arr_1=np.array(mers_results)
arr_1

array([[0.33 , 0.55 , 0.66 ],
       [0.44 , 0.65 , 0.23 ],
       [0.324, 0.567, 0.45 ]])

In [39]:
arr_1.ndim

2

In [40]:
arr_1.dtype

dtype('float64')

In [41]:
# indexing

print(arr_1[1])

[0.44 0.65 0.23]


In [42]:
#slicing

print(arr_1[0:1,1:2])

[[0.55]]


In [43]:
#multiply 
arr_1*7

array([[2.31 , 3.85 , 4.62 ],
       [3.08 , 4.55 , 1.61 ],
       [2.268, 3.969, 3.15 ]])

In [44]:
# mean, median

np.mean(mers_results)

np.float64(0.46677777777777785)

In [45]:
np.mean(masters_results)

np.float64(97.36)

In [46]:
np.median(sars_result)

np.float64(0.555)

In [47]:
np.median(masters_results)

np.float64(99.0)

In [48]:
# maximum

np.max(masters_results)

np.float64(99.9)

In [49]:
np.max(sars_result)

np.float64(0.776)

In [50]:
np.max(mers_results)

np.float64(0.66)

In [51]:
# minimum
np.min(masters_results)

np.float64(90.0)

In [52]:
np.min(mers_results)

np.float64(0.23)

In [53]:
np.min(sars_result)

np.float64(0.333)